spring:
  flyway:
      enabled: true
      url: jdbc:postgresql://localhost:5432/postgres
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      locations: classpath:db/migration
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true